### ISSUE TITLE
quantumfusion no longer on maven

### ISSUE THREAD

**Issue by epicbuilder2007** [QuantumFusionMC/DashLoader-Core#4]
Hey, where am I supposed to get the "hyphen:0.1" needed to build this thing when 

1. https://repo.maven.apache.org/maven2/dev/quantumfusion/hyphen/0.1/hyphen-0.1.pom does not exist anymore
2. there doesn't seem to be a way to download this?

**Comment by alphaqu** [comment]
use quantumfusion.dev/maven/ instead.

**Comment by epicbuilder2007** [comment]
wow that's quick. Ok.
